// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type INTERACTION_TYPE int32

const (
	INTERACTION_TYPE_PICK_UP      INTERACTION_TYPE = 0
	INTERACTION_TYPE_SCREEN_TOUCH INTERACTION_TYPE = 1
)

var INTERACTION_TYPE_name = map[int32]string{
	0: "PICK_UP",
	1: "SCREEN_TOUCH",
}
var INTERACTION_TYPE_value = map[string]int32{
	"PICK_UP":      0,
	"SCREEN_TOUCH": 1,
}

func (x INTERACTION_TYPE) String() string {
	return proto.EnumName(INTERACTION_TYPE_name, int32(x))
}
func (INTERACTION_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_1a3c39378ce6b724, []int{0}
}

type Event struct {
	ProductId            string               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName          string               `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InteractionType      INTERACTION_TYPE     `protobuf:"varint,4,opt,name=interaction_type,json=interactionType,proto3,enum=protos.INTERACTION_TYPE" json:"interaction_type,omitempty"`
	ButtonName           string               `protobuf:"bytes,5,opt,name=button_name,json=buttonName,proto3" json:"button_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_1a3c39378ce6b724, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Event) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Event) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Event) GetInteractionType() INTERACTION_TYPE {
	if m != nil {
		return m.InteractionType
	}
	return INTERACTION_TYPE_PICK_UP
}

func (m *Event) GetButtonName() string {
	if m != nil {
		return m.ButtonName
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "protos.Event")
	proto.RegisterEnum("protos.INTERACTION_TYPE", INTERACTION_TYPE_name, INTERACTION_TYPE_value)
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_1a3c39378ce6b724) }

var fileDescriptor_event_1a3c39378ce6b724 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0x8d, 0x3a, 0xa5, 0x5f, 0x87, 0x96, 0x9c, 0xca, 0x40, 0x56, 0x3d, 0x15, 0x0f, 0x1d,
	0xce, 0x8b, 0x57, 0x29, 0x05, 0x8b, 0xd0, 0x95, 0x98, 0x1d, 0x3c, 0x85, 0x76, 0x8d, 0xa3, 0x60,
	0x93, 0xd0, 0x7e, 0x15, 0xf6, 0x93, 0xfd, 0x17, 0xb2, 0x66, 0x55, 0xd9, 0x29, 0xe4, 0xcd, 0xf3,
	0xbe, 0x3c, 0x04, 0x5c, 0xf9, 0x25, 0x15, 0x46, 0xa6, 0xd5, 0xa8, 0xe9, 0xc5, 0x70, 0x74, 0xb3,
	0xf9, 0x56, 0xeb, 0xed, 0xa7, 0x5c, 0x0c, 0xd7, 0xb2, 0xff, 0x58, 0x60, 0xdd, 0xc8, 0x0e, 0x8b,
	0xc6, 0x58, 0xf0, 0xee, 0x9b, 0xc0, 0x24, 0xd9, 0x17, 0xe9, 0x0d, 0x80, 0x69, 0x75, 0xd5, 0x6f,
	0x50, 0xd4, 0x95, 0x4f, 0x02, 0x12, 0x3a, 0xcc, 0x39, 0x24, 0x69, 0x45, 0x6f, 0x61, 0x3a, 0x3e,
	0xab, 0xa2, 0x91, 0xfe, 0xe9, 0x00, 0xb8, 0x87, 0x2c, 0x2b, 0x1a, 0x49, 0x9f, 0xc0, 0xf9, 0x9d,
	0xf7, 0xcf, 0x02, 0x12, 0xba, 0xcb, 0x59, 0x64, 0x05, 0xa2, 0x51, 0x20, 0xe2, 0x23, 0xc1, 0xfe,
	0x60, 0x1a, 0x83, 0x57, 0x2b, 0x94, 0x6d, 0xb1, 0xc1, 0x5a, 0x2b, 0x81, 0x3b, 0x23, 0xfd, 0xf3,
	0x80, 0x84, 0x57, 0x4b, 0xdf, 0x36, 0xbb, 0x28, 0xcd, 0x78, 0xc2, 0x9e, 0x63, 0x9e, 0xae, 0x32,
	0xc1, 0xdf, 0xf3, 0x84, 0x5d, 0xff, 0x6b, 0xf0, 0x9d, 0x91, 0x74, 0x0e, 0x6e, 0xd9, 0x23, 0x6a,
	0x65, 0x05, 0x27, 0x83, 0x20, 0xd8, 0x68, 0xef, 0x77, 0xff, 0x00, 0xde, 0xf1, 0x0a, 0x75, 0xe1,
	0x32, 0x4f, 0xe3, 0x57, 0xb1, 0xce, 0xbd, 0x13, 0xea, 0xc1, 0xf4, 0x2d, 0x66, 0x49, 0x92, 0x09,
	0xbe, 0x5a, 0xc7, 0x2f, 0x1e, 0x29, 0xed, 0x3f, 0x3e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9b,
	0x0c, 0x68, 0x34, 0x5d, 0x01, 0x00, 0x00,
}
